Repository PinguDevTeam/ICF-MI-framework, pull requests merged in 2022-11, with the labels that each got.

#4 Add templates to create repository structure
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/todo_item.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, chore

#9 Feat/sahil/7
  .pre-commit-config.yaml
  README.md
Labels: documentation, enhancement

#18 Feat/sahil/6
  GIM/__init__.py
  GIM/template_GIM_documentation.py
  LSTM/__init__.py
  LSTM/template_LSTM_documentation.py
  README.md
  TTICE/__init__.py
  TTICE/template_TT_ICE_documentation.py
  scripts/configure_sphinx.sh
  scripts/create_documentation.sh
Labels: documentation, enhancement

#24 (feat) Add Formatting Linting actions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/todo_item.md
  .github/workflows/formattinLinting.yml
Labels: enhancement, chore

#28 (fix/pre-commit) Make Flake and Black 88 character
  .pre-commit-config.yaml
Labels: bug

#37 Flake error hotfix
  .pre-commit-config.yaml
Labels: bug, chore
